version: "3.8"

services:

  fluentd:
    container_name: fluentd
    restart: always
    image: chq/fluentd:v1.16
    volumes:
      - $PWD/fluent-opensearch.conf:/fluentd/etc/fluent.conf:ro
      ## For reading/writing log files by fluentd
      - $PWD/logs:/opt/log:ro
      - $PWD/positions:/opt/positions:rw
      ## Use host's timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fluent_net
    ports:
      ## Use Fluentd as centralized log ingester
      - "24224:24224"
    environment:
      ## Use independent timezone for this container
      - TZ=Asia/Tehran
    ## Use -v for fluentd DEBUG logs and -vv for TRACE logs
    ## For additional plugins dir use -p <plugins_dir> option
    ## Use --dry-run to validate config file
    command: -c /fluentd/etc/fluent.conf -v -p /fluentd/plugins --dry-run

networks:
  fluent_net:
    driver: bridge