version: "3"

services:

  fluentd:
    container_name: fluentd
    restart: always
    image: chq/fluentd:v1.16
    volumes:
      - $PWD/fluent-opensearch.conf:/fluentd/etc/fluent.conf:ro
      # For reading/writing log files by fluentd
      - /home/javad/TidDev/clr-returned-backend/log:/opt/logs:ro
      - /home/javad/TidDev/clr-returned-backend/log/positions:/opt/logs/positions:rw
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Tehran
    ports:
      - "24224:24224"
    # For giving plugins dir use -p <plugins_dir> option
    command: -c /fluentd/etc/fluent.conf -v
