services:
  infinispan-1:
    image: quay.io/infinispan/server:14.0.28.Final
    container_name: infinispan-1
    restart: always
    environment:
      - TZ=Asia/Tehran
      - USER=admin
      # Note: you need to escape dollar sign
      - PASS=Test$$1234
      - JGROUPS_DISCOVERY_EXTERNAL_IP=192.168.61.30
      - JGROUPS_DISCOVERY_PORT=7800
      - JGROUPS_JDBC_DRIVER=com.mysql.cj.jdbc.Driver
      - JGROUPS_JDBC_URL=jdbc:mysql://192.168.100.117:3306/test_keycloak_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      - JGROUPS_DB_USER=root
      - JGROUPS_DB_PASSWORD=root
      - ISPN_PUBLIC_IP=192.168.61.30
      - ISPN_PUBLIC_PORT=11222
      - ISPN_ADMIN_PORT=49152
    network_mode: "host"
    #networks:
    #  - infinispan_net
#      - keycloak-net
    ports:
      - "11222:11222" ## We configured it jut for HotRod (defaults to HotRod & Rest)
      - "7800:7800"   ## JGroups
      - "49152:49152" ## Admin Console (Rest)
      # - "11221:11221" ## is used for memcached API (disabled in config file)
    volumes:
      - ./conf/infinispan.xml:/opt/infinispan/server/conf/infinispan.xml:ro
      ## Find appropriate database JAR files in Keycloak-23/lib directory: exclude io.quarkus.quarkus-jdbc-*.jar files
      ### Database JDBC driver (needed for JDBC ping jgroup)
      - ./lib/com.mysql.mysql-connector-j-8.2.0.jar:/opt/infinispan/lib/com.mysql.mysql-connector-j-8.2.0.jar:ro
      #- ./lib/org.postgresql.postgresql-42.6.0.jar:/opt/infinispan/lib/org.postgresql.postgresql-42.6.0.jar:ro
      - ./lib/com.oracle.database.jdbc.ojdbc11-23.3.0.23.09.jar:/opt/infinispan/lib/com.oracle.database.jdbc.ojdbc11-23.3.0.23.09.jar:ro
      - ./lib/com.oracle.database.nls.orai18n-23.3.0.23.09.jar:/opt/infinispan/lib/com.oracle.database.nls.orai18n-23.3.0.23.09.jar:ro
      #- ./lib/com.microsoft.sqlserver.mssql-jdbc-12.2.0.jre11.jar:/opt/infinispan/lib/com.microsoft.sqlserver.mssql-jdbc-12.2.0.jre11.jar:ro
      ### Keycloak models and marshallers needed to talk infinispan
      - ./lib/org.keycloak.keycloak-model-infinispan-23.0.7.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-model-infinispan-23.0.7.jar:ro
      - ./lib/org.keycloak.keycloak-core-23.0.7.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-core-23.0.7.jar:ro
      - ./lib/org.keycloak.keycloak-server-spi-23.0.7.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-server-spi-23.0.7.jar:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  infinispan-2:
    image: quay.io/infinispan/server:14.0.28.Final
    container_name: infinispan-2
    restart: always
    environment:
      - TZ=Asia/Tehran
      - USER=admin
      # Note: you need to escape dollar sign
      - PASS=Test$$1234
      - JGROUPS_DISCOVERY_EXTERNAL_IP=192.168.61.30
      - JGROUPS_DISCOVERY_PORT=7900
      - JGROUPS_JDBC_DRIVER=com.mysql.cj.jdbc.Driver
      - JGROUPS_JDBC_URL=jdbc:mysql://192.168.100.117:3306/test_keycloak_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      - JGROUPS_DB_USER=root
      - JGROUPS_DB_PASSWORD=root
      - ISPN_BIND_ADDRESS=192.168.61.30
    #networks:
    #  - infinispan_net
    network_mode: "host"
    ports:
      - "11322:11222"
      - "7900:7900"
      # - "11221:11221" ## form memcached API
    volumes:
      - ./conf/infinispan.xml:/opt/infinispan/server/conf/infinispan.xml:ro
      ## Find appropriate database JAR files in Keycloak-23/lib directory: exclude io.quarkus.quarkus-jdbc-*.jar files
      ### Database JDBC driver (needed for JDBC ping jgroup)
      - ./lib/com.mysql.mysql-connector-j-8.2.0.jar:/opt/infinispan/lib/com.mysql.mysql-connector-j-8.2.0.jar:ro
      #- ./lib/org.postgresql.postgresql-42.6.0.jar:/opt/infinispan/lib/org.postgresql.postgresql-42.6.0.jar:ro
      - ./lib/com.oracle.database.jdbc.ojdbc11-23.3.0.23.09.jar:/opt/infinispan/lib/com.oracle.database.jdbc.ojdbc11-23.3.0.23.09.jar:ro
      - ./lib/com.oracle.database.nls.orai18n-23.3.0.23.09.jar:/opt/infinispan/lib/com.oracle.database.nls.orai18n-23.3.0.23.09.jar:ro
      #- ./lib/com.microsoft.sqlserver.mssql-jdbc-12.2.0.jre11.jar:/opt/infinispan/lib/com.microsoft.sqlserver.mssql-jdbc-12.2.0.jre11.jar:ro
      ### Keycloak models and marshallers needed to talk infinispan
      - ./lib/org.keycloak.keycloak-model-infinispan-23.0.7.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-model-infinispan-23.0.7.jar:ro
      - ./lib/org.keycloak.keycloak-core-23.0.7.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-core-23.0.7.jar:ro
      - ./lib/org.keycloak.keycloak-server-spi-23.0.7.jar:/opt/infinispan/server/lib/org.keycloak.keycloak-server-spi-23.0.7.jar:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  keycloak-net:
    name: keycloak-23_keycloak-net
    external: true

  infinispan_net:
    driver: bridge
