version: "3"

services:

  fluentd:
    container_name: chq-logger
    restart: always
    image: chq/fluentd:v1.15
    volumes:
      - $PWD/fluent.conf:/fluentd/etc/fluent.conf
      - $PWD/log:/fluentd/log
    #networks:
    #  - test_net  
    ports:
      - "24224:24224"
    command: -c /fluentd/etc/fluent.conf -v

  # app:
  #   restart: always
  #   ports:
  #     - "4000:8080"
  #   networks:
  #       - test_net
  #   depends_on:
  #     - fluentd
  #   environment:
  #     - DEBUG
  #   logging:
  #     driver: fluentd
  #     options:
  #       fluentd-address: "localhost:24224"
  #       fluentd-async-connect: "true"
  #       tag: docker.global

# networks:
#   test_net:
#     driver: bridge