version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:8.5.2
    container_name: elasticsearch
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
      - /opt/elastic-snapshots:/opt/elastic-snapshots
    environment:
      - xpack.security.enabled=false
      - path.repo=["/opt/elastic-snapshots"]
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - TZ=Asia/Tehran
#      - ELASTIC_PASSWORD=changeme
      - node.name=chq-elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200

  kibana:
    image: kibana:8.5.2
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data-volume:
    driver: local
