version: '3.7'

# Common configurations for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-09-16T01-01-47Z
  command: server --console-address ":9000" /mnt/data
  ports:
    - "9000:9000"
    - "9090:9090"
  environment:
    - MINIO_ACCESS_KEY=chq
    - MINIO_SECRET_KEY=supersecret
    - MINIO_PROMETHEUS_AUTH_TYPE=public
    - MINIO_UPDATE=off
  healthcheck:
    test: ["cmd", "curl", "-f", "http://localhost:9000/minio/health/live""]
    interval: 30s
    timeout: 20s
    retries: 3

service:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - type: bind
        source: ./data
        target: /mnt/data
      - type: bind
        source: ./conf/minio.conf
        target: /etc/config.env
