version: "3"

services:

  jobmanager:
    image: flink:1.16-java11
    ports:
      - "8081:8081"
    command: jobmanager
    ## If you need to pass argument into command line (Not recommended, use environment variables):
    # command: jobmanager -D jobmanager.rpc.address=host
    #volumes:
    ## Config file must be writable by docker container
    #  - $PWD/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml:rw
    #  - $PWD/log4j.properties:/opt/flink/conf/log4j.properties:ro
    #  - /etc/timezone:/etc/timezone:ro
    #  - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Tehran
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: flink:1.16-java11
    depends_on:
      - jobmanager
    command: taskmanager
    ## If you need to pass argument into command line (Not recommended, use environment variables):
    # command: taskmanager -D jobmanager.rpc.address=host
    scale: 1
    #volumes:
    #  - /etc/timezone:/etc/timezone:ro
    #  - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Tehran
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2    

  sql-client:
    image: flink:1.16-java11
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    environment:
      - TZ=Asia/Tehran
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager

networks:
   flink_network:
     driver: bridge